# Generated by Django 4.2.16 on 2026-07-19 15:42

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=core.models.generate_client_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=core.models.generate_client_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('picture_key', models.CharField(blank=True, default='', max_length=500)),
                ('picture_content_type', models.CharField(blank=True, default='', max_length=120)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
