# Generated by Django 4.2.16 on 2026-07-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='new', max_length=20),
        ),
    ]
